[package]
name = "dobby"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.44"
clap = { version = "=4.5.47", features = ["derive"] }
env = "1.0.1"
rumqttc = "0.25.1"
rustls = "0.23.36"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread", "time"] }
